name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Install optipng
        run: sudo apt-get install -y optipng

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build sprites
        run: |
          npm run build-sprites
          cd release/sprites
          tar -cf - * | gzip -9 > ../sprites.tar.gz

      - name: Build styles
        run: npm run build-styles

      - name: Build lib
        run: npm run build-browser

      - name: Get version
        run: 'echo "RELEASE_TAG=v$(jq -r ''.version'' package.json)" >> $GITHUB_ENV'

      - name: Upload file to release
        run: gh release upload $RELEASE_TAG sprites.tar.gz styles.tar.gz versatiles-style.tar.gz --clobber
        working-directory: release

      - name: Update release
        run: gh release edit $RELEASE_TAG --draft=false --latest --prerelease=false
